<?xml version="1.0"?>
<robot name="superchick" xmlns:xacro="http://www.ros.org/wiki/xacro">

   <!-- General Properties -->
   <!-- Lekan Ogunmolu | November 2016 -->
   <xacro:property name="bladder_length" value="0.15748" />
   <xacro:property name="bladder_width" value="${bladder_length}" />
   <xacro:property name="bladder_thickness" value="0.0508" />
   <xacro:property name="bladder_constant" value="2" />
   <xacro:property name="left_bladder_x" value="${bladder_width/2}" />
   <xacro:property name="mass" value="1e-2" />
   <xacro:property name="inertia_mom" value="${mass/12}" />
   
   <link name="right_bladder">
     <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <geometry>
         <box size="${bladder_length} ${bladder_width} ${bladder_thickness}" />
       </geometry>
       <material name="bladder_color"/>
       <origin xyz="0 0 0" rpy="0 0 0" />
     </visual>

     <collision>
       <geometry>        
        <box size="${bladder_length} ${bladder_width} ${bladder_thickness}" />
       </geometry>
       <origin xyz="0 0 0" rpy="0 0 0" />
     </collision>

     <inertial>
       <mass value="${mass}"/>
       <inertia ixx="${mass/12}" ixy="0.0" ixz="0.0" 
        iyy="${inertia_mom}" iyz="0.0000" 
        izz="${inertia_mom}"/>
     </inertial>
   </link>

   <link name="left_bladder">
     <visual>
       <origin xyz="0 ${0.1/2} 0" rpy="0 0 0" />
       <geometry>
         <box size="${bladder_length} ${bladder_width} ${bladder_thickness}" />
       </geometry>
       <material name="bladder_color"/>
       <origin xyz="0 ${0.1/2} 0" rpy="0 0 0" />
     </visual>

     <collision>
       <geometry>        
        <box size="${bladder_length} ${bladder_width} ${bladder_thickness}" />
       </geometry>
       <origin xyz="0 ${0.1/2} 0" rpy="0 0 0" />
     </collision>

     <inertial>
       <mass value="${mass}"/>
       <inertia ixx="${mass/12}" ixy="0.0" ixz="0.0" 
        iyy="${inertia_mom}" iyz="0.0000" 
        izz="${inertia_mom}"/>
     </inertial>
   </link>

   <link name="big_bladder_link">
     <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <geometry>
         <box size="${bladder_constant*bladder_length} ${bladder_constant*bladder_width} ${bladder_thickness}" />
       </geometry>
       <material name="bladder_color"/>
       <origin xyz="0 0 0" rpy="0 0 0" />
     </visual>

     <collision>
       <geometry>       
        <box size="${bladder_constant*bladder_length} ${bladder_constant*bladder_width} ${2*bladder_thickness}" />
       </geometry>
       <origin xyz="0 0 0" rpy="0 0 0" />
     </collision>

     <inertial>
       <mass value="${mass}"/>
       <inertia ixx="${mass/12}" ixy="0.0" ixz="0.0" 
        iyy="${inertia_mom}" iyz="0.0000" 
        izz="${inertia_mom}"/>
     </inertial>
   </link>

</robot>
<!-- 
Mesh Bounding Box Size 469.900360 107.148705 279.399994
Mesh Bounding Box Diag 557.092041 
Mesh Volume is 7880078.000000
Mesh Surface is 290806.531250
Thin shell barycenter 229.254868 65.684402 138.717850
Center of Mass is 224.210358 65.684280 139.608521
Inertia Tensor is :
| 34788040704.000000 48117.027344 163155712.000000 |
| 48117.027344 145745428480.000000 279917.406250 |
| 163155712.000000 279917.406250 119543234560.000000 |
Principal axes are :
| 0.999998 0.000000 0.001925 |
| -0.000000 1.000000 -0.000011 |
| -0.001925 0.000011 0.999998 |
axis momenta are :
| 34787725312.000000 145745428480.000000 119543545856.000000 | 
-->