<?xml version="1.0"?>
<robot name="superchick" xmlns:xacro="http://www.ros.org/wiki/xacro">

   <!-- General Properties -->
   <xacro:property name="bladder_pos_x" value="-0.7" />
   <xacro:property name="bladder_pos_y" value="-0.35" />
   <xacro:property name="damping" value="0.1" />
   <xacro:property name="friction" value="0.2" />
  <!-- This file contains the table and bladder descriptions -->
   <xacro:include filename="$(find superchick)/material.xacro" />
   <xacro:include filename="$(find superchick)/table.xacro" />
   <xacro:include filename="$(find superchick)/bladders.xacro" />
   <xacro:include filename="$(find superchick)/headnball.xacro" />
   <xacro:include filename="$(find superchick)/cage.xacro" />
   <xacro:include filename="$(find superchick)/vicon.xacro" />
   <xacro:include filename="$(find superchick)/superchick.gazebo" />

   <!-- table link to bladders -->
  <joint name="table_to_big_bladder" type="fixed">
    <parent link="table_top"/>
    <child link="big_bladder_link"/>
    <limit effort="200.0" lower="0.1016" upper="0.1016" velocity="1.0" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-0.05" soft_upper_limit="0.05" />
    <origin xyz="${-(table_top_length)/2 + 0.23} 0 ${1e-1/3}" rpy="${0} 0 ${0}" />
  </joint>

  <joint name="table_to_rightneckbladder" type="fixed">
    <parent link="table_top"/>
    <child link="right_bladder"/>
    <limit effort="200.0" lower="0.1016" upper="0.1016" velocity="1.0" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-0.05" soft_upper_limit="0.05" />
    <origin xyz="${-(table_top_length)/3 + 0.15} 0.12 ${1e-1/3.2}" rpy="${0} 0 ${0}" />
  </joint>

  <joint name="table_to_leftneckbladder" type="fixed">
    <parent link="table_top"/>
    <child link="left_bladder"/>
    <limit effort="200.0" lower="0.1016" upper="0.1016" velocity="1.0" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-0.05" soft_upper_limit="0.05" />
    <origin xyz="${-(table_top_length)/3 + 0.15} -0.12 ${1e-1/3.2}" rpy="${0} 0 ${0}" />
  </joint>

  <!-- Actuator Links -->
  <joint name="bigbladder_to_head" type="continuous">
    <axis xyz="1 0 0" rpy="0 0 0" />
    <parent link="big_bladder_link"/>
    <child link="headnball_link"/>
    <limit effort="200.0" lower="-0.1016" upper="0.1016" velocity="1.0" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-0.0" soft_upper_limit="0.3" />
    <origin xyz="${(1e-1/2)+1e-1} ${(table_top_width)/6} 0" rpy="0 0 ${M_PI/2}" />
  </joint>

  <joint name="rightbladder_to_neck" type="continuous">
    <axis xyz="1 -1 0" rpy="0 0 0" />
    <parent link="right_bladder"/>
    <child link="headnball_link"/>
    <limit effort="200.0" lower="-0.1016" upper="0.1016" velocity="1.0" />
    <dynamics damping="${damping}" friction="${friction}" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="0.0" soft_upper_limit="0.3"/>
    <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
  </joint>

  <joint name="leftbladder_to_neck" type="continuous">
    <axis xyz="1 1 0" rpy="0 0 0" />
    <parent link="left_bladder"/>
    <child link="headnball_link"/>
    <limit effort="200.0" lower="-0.1016" upper="0.1016" velocity="1.0" />
    <dynamics damping="${damping}" friction="${friction}" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="0.0" soft_upper_limit="0.3" />
    <dynamics damping="${damping}" friction="${friction}" />
    <origin xyz="0 0.25 0" rpy="0 0 ${M_PI/2}" />
  </joint>

  <joint name="tableTop_to_basePanel" type="fixed">
    <parent link="table_top"/>
    <child link="base_panel"/>
    <origin xyz="${-(table_top_length)/2 + 0.15} 0 ${1e-1/8}" rpy="${0} 0 ${M_PI/2}" />
  </joint>

  <joint name="vicon_to_world" type="fixed">
    <parent link="world"/>
    <child link="vicon_frame"/>
    <origin xyz="-5 -4 2.00" rpy="0 0 0" />
  </joint>

</robot>
