#! /bin/bash
echo -e "Clean current directory? [yn]"
read res

is_yes() {
        yesses={y,Y,yes,Yes,YES}
        if [[ $yesses =~ $1 ]]; then
                echo 1
        fi
        }

is_no() {
        noses={n,N,no,No,No}
        if [[ $noses =~ $1 ]]; then
                echo 1
        fi
        }

if [ $(is_yes $res) ]; then
   echo -e "cleaning up cwd"
   rm -rf *;
else
   echo "Proceeding with compilation"
fi

cmake ..; make -j8; make install

IAB_Launcher
