#! /bin/bash
# see https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
POSITIONAL=()
while [[ $# -gt 0 ]]
do key="$1"

case $key in
  -b|--build) #  clean current working directory
  build="$2"
  shift # past argument
  shift # past value
  ;;
  -c|--clean) #  clean current working directory
  res="$2"
  shift # past argument
  shift # past value
  ;;
  -l|--launch)  # launch iab executable?
  launch="$2"
  shift # past arg
  shift # past value
  ;;
  -s|--soro)  # launch iab executable?
  soro="$2"
  shift # past arg
  shift # past value
  ;;
  *) # unknown option
  POSITIONAL+=("$1") # save in array for later use
  shift # past arg
  ;;
esac
done
set -- "${POSITION[@]}" # restore positional parameters

if [[ -z "$build" ]]; then
  echo -e "usage: `basename $0` [-b] [-c] [-l] [-s]\n\t-c [build [clean current build directory]\n\t-l launch IAB exec after building\n\t-s launch soro exec after building?"
  echo -e "\te.g. ../`basename $0` -b n -c n -l n -s y
"
  exit 1
fi

# echo -e "Clean current directory? [yn]"
# read res

is_yes() {
        yesses={y,Y,yes,Yes,YES}
        if [[ $yesses =~ $1 ]]; then
                echo 1
        fi
        }

is_no() {
        noses={n,N,no,No,No}
        if [[ $noses =~ $1 ]]; then
                echo 1
        fi
        }

if [[ $(is_yes $build) ]]; then
   echo -e "re-building the executables and shared libraries"
   rm -rf *;
  if [[ $(is_yes $res) ]]; then
     echo -e "cleaning up cwd"
     rm -rf *;
  fi
  cmake -DBoost_NO_BOOST_CMAKE=ON ..;

  if [[ -f "$SOFA_ROOT/lib/libIAB.so" ]]; then
    echo "removing \"$SOFA_ROOT/lib/libIAB*.so\" "
    rm "$SOFA_ROOT/lib/libIABTetra.so"
    rm "$SOFA_ROOT/lib/libIAB.so"
  elif [[ -f "$SOFA_ROOT/lib/libIAB.dylib" ]]; then
    echo "removing \"$SOFA_ROOT/lib/libIAB*.dylib\" "
    rm "$SOFA_ROOT/lib/libIAB.dylib"
    rm "$SOFA_ROOT/lib/libIABTetra.dylib"
  fi

  make DESTDIR="$SOFA_ROOT/lib" -j8; make install
fi

   # echo "Runing already build executable"

if [ $(is_yes $launch) ]; then
  ./IAB_Launcher -g true
elif [[ $(is_yes $soro) ]]; then
  #echo -e "Run SingleIAB with GUI? "
  ./SingleIAB -g true
else
  exit 0
fi
