<?xml version="1.0"?>
<robot name="superchick" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Description: Head Cage

	 Author: Alex Tomkovich, September 27, 2016
	 Modified: Lekan Ogunmolu Nov. 18, 2016
 	-->

	<!-- Panel Properties -->
	<xacro:property name="side_panel_length" value=".231775" />
	<xacro:property name="panel_12_oc_length" value=".4700" /> 

	<xacro:property name="panel_height" value=".200025" />
	<xacro:property name="panel_thickness" value=".0047625" />
	<xacro:property name="base_panel_length" value=".5842" />
	<xacro:property name="base_panel_width" value=".2794" />
	<xacro:property name ="distance_panel_12_oc_from_center" value ="${(base_panel_width/2) - .04572}" />

	<link name="base_panel">
		<visual>
			<geometry>
				<box size="${base_panel_length} ${base_panel_width} ${panel_thickness}" />
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<material name="panel_color" />
		</visual>

		<collision>
			<geometry>
				<box size="${base_panel_length} ${base_panel_width} ${panel_thickness}" />
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0" />
		</collision>

		<inertial>
		  <mass value="${mass}"/>
		  <inertia ixx="${mass/12}" ixy="0.0" ixz="0.0" 
		   iyy="${inertia_mom}" iyz="0.0000" 
		   izz="${inertia_mom}"/>
		</inertial>
	</link>
	

	<!-- 12:00 panel -->
	<link name="panel_12_oc">
		<visual>
			<geometry>
				<box size="${panel_12_oc_length} ${panel_height} ${panel_thickness}" />
			</geometry>
			<material name="panel_color" />
			<origin xyz="0 0 0" rpy="${(M_PI/2)} 0 0" />
		</visual>

		<collision>
			<geometry>
				<box size="${panel_12_oc_length} ${panel_height} ${panel_thickness}" />
			</geometry>
			<origin xyz="0 0 0" rpy="${(M_PI/2)} 0 0" />
		</collision>

		<inertial>
		  <mass value="${mass}"/>
		  <inertia ixx="${mass/12}" ixy="0.0" ixz="0.0" 
		   iyy="${inertia_mom}" iyz="0.0000" 
		   izz="${inertia_mom}"/>
		</inertial>
	</link>
	

	<!-- Join 12:00 Panel to base_panel -->
	<joint name="base_panel_to_12oc" type="fixed">
		<parent link="base_panel"/>
		<child link="panel_12_oc"/>
		<origin xyz="0 ${distance_panel_12_oc_from_center} ${(panel_thickness/2) + (panel_height/2)}" />
	</joint>

	<!-- 9:00 Panel -->
	<link name="panel_9_oc">
		<visual>
			<origin xyz="0 0 0" rpy="${(M_PI/2)} 0 ${(M_PI/2)}" />
			<geometry>
				<box size="${side_panel_length} ${panel_height} ${panel_thickness}" />
			</geometry>
			<material name="panel_color" />
		</visual>

		<collision>
			<geometry>
				<box size="${side_panel_length} ${panel_height} ${panel_thickness}" />
			</geometry>
			<origin xyz="0 0 0" rpy="${(M_PI/2)} 0 ${(M_PI/2)}" />
		</collision>

		<inertial>
		  <mass value="${mass}"/>
		  <inertia ixx="${mass/12}" ixy="0.0" ixz="0.0" 
		   iyy="${inertia_mom}" iyz="0.0000" 
		   izz="${inertia_mom}"/>
		</inertial>
	</link>
	

	<!-- Join 9:00 Panel to 12:00 Panel -->
	<joint name="12oc_to_9oc" type="fixed">
		<parent link="panel_12_oc"/>
		<child link="panel_9_oc"/>
		<origin xyz="${-((panel_12_oc_length/2) + (panel_thickness/2))} ${-((side_panel_length/2) - (panel_thickness/2))} 0" />
	</joint>

	<!-- 3:00 Panel -->
	<link name="panel_3_oc">
		<visual>
			<origin xyz="0 0 0" rpy="${(M_PI/2)} 0 ${(M_PI/2)}" />
			<geometry>
				<box size="${side_panel_length} ${panel_height} ${panel_thickness}" />
			</geometry>
			<material name="panel_color" />
		</visual>
		<collision>
			<geometry>
				<box size="${side_panel_length} ${panel_height} ${panel_thickness}" />
			</geometry>
			<origin xyz="0 0 0" rpy="${(M_PI/2)} 0 ${(M_PI/2)}" />
		</collision>

		<inertial>
		  <mass value="${mass}"/>
		  <inertia ixx="${mass/12}" ixy="0.0" ixz="0.0" 
		   iyy="${inertia_mom}" iyz="0.0000" 
		   izz="${inertia_mom}"/>
		</inertial>
	</link>
	
	<!-- Join 3:00 Panel to 12:00 Panel -->
	<joint name="12oc_to_3oc" type="fixed">
		<parent link="panel_12_oc"/>
		<child link="panel_3_oc"/>
		<origin xyz="${(panel_12_oc_length/2) + (panel_thickness/2)} ${-((side_panel_length/2) - (panel_thickness/2))} 0" />
	</joint>

</robot>


