#ifndef INITTETRAHEDRONMOONEYRIVLINFFPLUGIN_H
#define INITTETRAHEDRONMOONEYRIVLINFFPLUGIN_H

#include <sofa/helper/system/config.h>

#define SOFA_TARGET TetraMooneyRivlinFEMForceFieldPlugin
#ifdef SOFA_BUILD_IABTETRAPLUGIN
# define SOFA_IABTetraPlugin_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
# define SOFA_IABTetraPlugin_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif
