#ifndef INITTETRAHEDRONMOONEYRIVLINFFPLUGIN_H
#define INITTETRAHEDRONMOONEYRIVLINFFPLUGIN_H

#include <sofa/helper/system/config.h>

#define SOFA_TARGET TetraMooneyRivlinPlugin
#ifdef SOFA_BUILD_TETRAMOONRIVPLUGIN
# define SOFA_TETRAMOONRIVPlugin_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
# define SOFA_TETRAMOONRIVPlugin_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif
